name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'
      id: go

    - name: Check out code into go module directory
      uses: actions/checkout@v4

    - name: Test
      run: make test
